version: '3'
services:
  db:
    image: mysql:latest
    container_name: learning-integration-testing-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_it
    volumes:
      - /home/ubuntu/soft/mysql_docker/db:/var/lib/mysql